import { Post } from './types';

export const mockPosts: Post[] = [
  {
    id: '1',
    accountName: 'Socionix',
    date: '05/15/2026, 04:32 PM',
    type: 'CAROUSEL',
    platform: 'instagram',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1588698505501-c30f40ced050?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1558980838-8fa19fcb1d28?auto=format&fit=crop&q=80&w=800'
    ],
    caption: 'Following the media launch of the ADV 390 in Bangalore, we collaborated with an FMSCI-promoted Enduro cross racing event that brought together biking enthusiasts. The event witnessed 100+ test rides, generating strong awareness. Riders shared highly positive feedback.',
    hashtags: ['#KTMAdventure', '#ADV390', '#ReadyToRace', '#EnduroExperience', '#RideTheExtreme'],
    outletsCount: 1,
    category: 'Brands',
    postedBy: 'Super Admin',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: [
      {
        id: 'o1',
        name: 'Kin Automotive Wynwood',
        time: '05/15/2026, 04:35 PM',
        code: 'U12382',
        zone: 'SOUTH',
        region: 'FLORIDA',
        city: 'MIAMI',
        status: 'Published',
        platform: 'instagram'
      }
    ]
  },
  {
    id: '2',
    accountName: 'Meet Socionix',
    date: '05/14/2026, 03:48 PM',
    type: 'CAROUSEL',
    platform: 'instagram',
    image: 'https://images.unsplash.com/photo-1568910815124-7b9ebc7cb171?auto=format&fit=crop&q=80&w=800',
    images: [
      'https://images.unsplash.com/photo-1568910815124-7b9ebc7cb171?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1620059530419-74d6f0ac68a1?auto=format&fit=crop&q=80&w=800'
    ],
    caption: 'Following the media launch of the ADV 390 in Bangalore, we collaborated with an FMSCI-promoted event.',
    hashtags: ['#KTMAdventure', '#ADV390'],
    outletsCount: 1,
    category: 'Brands',
    postedBy: 'giriraj',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: []
  },
  {
    id: '3',
    accountName: 'Socionix',
    date: '05/14/2026, 03:35 PM',
    type: 'IMAGE',
    platform: 'instagram',
    image: 'https://images.unsplash.com/photo-1571188654261-7557117d6928?auto=format&fit=crop&q=80&w=800',
    caption: 'Following the media launch of the ADV 390 in Bangalore, we collaborated with an FMSCI-promoted event.',
    hashtags: ['#KTMAdventure'],
    outletsCount: 1,
    category: 'Brands',
    postedBy: 'giriraj',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: []
  },
  {
    id: '4',
    accountName: 'Socionix Motors',
    date: '05/13/2026, 11:20 AM',
    type: 'VIDEO',
    platform: 'facebook',
    image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=800',
    caption: 'Experience the thrill of the new test track with our latest performance exhaust system. Turn up the volume! 🔊',
    hashtags: ['#Performance', '#TestTrack', '#LoudPipes'],
    outletsCount: 5,
    category: 'Products',
    postedBy: 'admin',
    status: 'Published',
    publishedCount: 5,
    totalCount: 5,
    outlets: []
  },
  {
    id: '7',
    accountName: 'Socionix Life',
    date: '05/10/2026, 04:30 PM',
    type: 'REEL',
    platform: 'instagram',
    image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&q=80&w=800',
    caption: 'Behind the scenes at our latest photoshoot! 🎬✨ Watch the magic unfold as our team creates the perfect summer campaign.',
    hashtags: ['#BehindTheScenes', '#Photoshoot', '#SummerVibes', '#TeamWork'],
    outletsCount: 1,
    category: 'Brands',
    postedBy: 'sarah',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: []
  },
  {
    id: '8',
    accountName: 'Socionix Daily',
    date: '05/10/2026, 10:15 AM',
    type: 'STORY',
    platform: 'instagram',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    caption: 'Flash sale starting in 1 hour! Swipe up to save 50% on all accessories.',
    hashtags: ['#FlashSale', '#Discounts', '#ShopNow'],
    outletsCount: 1,
    category: 'Promotions',
    postedBy: 'admin',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: []
  },
  {
    id: '9',
    accountName: 'Socionix Design',
    date: '05/09/2026, 02:00 PM',
    type: 'COVER_IMAGE',
    platform: 'facebook',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200',
    caption: 'Welcome to our new official Facebook page style.',
    hashtags: ['#NewLook', '#Design', '#Update'],
    outletsCount: 1,
    category: 'Corporate',
    postedBy: 'marketing_team',
    status: 'Published',
    publishedCount: 1,
    totalCount: 1,
    outlets: []
  }
];
